# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gramar_mcmc <- function(y, family, X, coords, axis_partition, k, set_unif_bounds_in, beta_Vi, sigmasq_ab, tausq_ab, start_w, lambda, lambda_mask, theta, beta, tausq, mcmcsd, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, mcmc_startfrom = 0L, num_threads = 1L, which_hmc = 4L, adapting = FALSE, use_cache = TRUE, use_ps = TRUE, verbose = FALSE, debug = FALSE, print_every = FALSE, low_mem = FALSE, sample_beta = TRUE, sample_tausq = TRUE, sample_lambda = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_gramar_gramar_mcmc`, y, family, X, coords, axis_partition, k, set_unif_bounds_in, beta_Vi, sigmasq_ab, tausq_ab, start_w, lambda, lambda_mask, theta, beta, tausq, mcmcsd, mcmc_keep, mcmc_burn, mcmc_thin, mcmc_startfrom, num_threads, which_hmc, adapting, use_cache, use_ps, verbose, debug, print_every, low_mem, sample_beta, sample_tausq, sample_lambda, sample_theta, sample_w)
}

mgp_precision <- function(coords, xcoords_in, axis_partition, theta, tausq, num_threads = 1L, use_cache = TRUE, verbose = FALSE, debug = FALSE) {
    .Call(`_gramar_mgp_precision`, coords, xcoords_in, axis_partition, theta, tausq, num_threads, use_cache, verbose, debug)
}

gramar_mcmc_collapsed <- function(y, family, X, coords, axis_partition, k, set_unif_bounds_in, beta_Vi, sigmasq_ab, tausq_ab, start_w, lambda, lambda_mask, theta, beta, tausq, mcmcsd, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, mcmc_startfrom = 0L, num_threads = 1L, which_hmc = 4L, adapting = FALSE, use_cache = TRUE, use_ps = TRUE, verbose = FALSE, debug = FALSE, print_every = FALSE, low_mem = FALSE, sample_beta = TRUE, sample_tausq = TRUE, sample_lambda = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_gramar_gramar_mcmc_collapsed`, y, family, X, coords, axis_partition, k, set_unif_bounds_in, beta_Vi, sigmasq_ab, tausq_ab, start_w, lambda, lambda_mask, theta, beta, tausq, mcmcsd, mcmc_keep, mcmc_burn, mcmc_thin, mcmc_startfrom, num_threads, which_hmc, adapting, use_cache, use_ps, verbose, debug, print_every, low_mem, sample_beta, sample_tausq, sample_lambda, sample_theta, sample_w)
}

Cov_matern <- function(x, y, sigmasq, phi, nu, tausq, same, nThreads = 1L) {
    .Call(`_gramar_Cov_matern`, x, y, sigmasq, phi, nu, tausq, same, nThreads)
}

Cov_matern2 <- function(x, y, phi, same, twonu) {
    .Call(`_gramar_Cov_matern2`, x, y, phi, same, twonu)
}

Cov_matern_h <- function(h, sigmasq, phi, nu, tausq) {
    .Call(`_gramar_Cov_matern_h`, h, sigmasq, phi, nu, tausq)
}

Cov_powexp_h <- function(h, sigmasq, phi, nu, tausq) {
    .Call(`_gramar_Cov_powexp_h`, h, sigmasq, phi, nu, tausq)
}

gneiting2002_h <- function(h, u, a, c, beta) {
    .Call(`_gramar_gneiting2002_h`, h, u, a, c, beta)
}

kernp_xx <- function(Xcoords, kweights) {
    .Call(`_gramar_kernp_xx`, Xcoords, kweights)
}

kernp_xy <- function(Xcoords, Ycoords, kweights) {
    .Call(`_gramar_kernp_xy`, Xcoords, Ycoords, kweights)
}

kthresholdscp <- function(x, k) {
    .Call(`_gramar_kthresholdscp`, x, k)
}

uturbocolthreshold <- function(col1, thresholds) {
    .Call(`_gramar_uturbocolthreshold`, col1, thresholds)
}

split_ap <- function(membership, coords, thresholds) {
    .Call(`_gramar_split_ap`, membership, coords, thresholds)
}

cube_tcrossprod <- function(x) {
    .Call(`_gramar_cube_tcrossprod`, x)
}

summary_list_mean <- function(x, n_threads = 1L) {
    .Call(`_gramar_summary_list_mean`, x, n_threads)
}

summary_list_q <- function(x, q, n_threads = 1L) {
    .Call(`_gramar_summary_list_q`, x, q, n_threads)
}

